#   .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-.
#   ( L .'( i .'( f .'( e .'( S .'( t .'( o .'( l .'( e .'( n .'
#    `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(   `.(
#
# Plugin by KadotCom

# General

returnHP: 20 #  When a player is unbanned, their health will reset
MaxHP: 120 # HP that when reached, the player will not gain anymore health
banOnDeath: true # If set true the player will be banned when they lose all their hearts, if set to false the player will be put in spectator instead.
anyDeathRemovesHearts: true # If set false the player will only lose hearts if another player kills them.

# Permissions

permissions:
  # permission - The permission someone needs to run a permission based command.
  # permission-message - The message that appears when someone tries to run a command and doesn't have the correct permissions.
  # permissionToDoEverything - The permission someone needs to run all permission based commands.
  sethealth:
    permission: "lifestolen.sethealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  addhealth:
    permission: "lifestolen.addhealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  removehealth:
    permission: "lifestolen.removehealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  resethp:
    permission: "lifestolen.resethealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  giveheart:
    permission: "lifestolen.giveheart"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command. You will have to craft a heart."
  reload:
    permission: "lifestolen.reload"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  permissionToDoEverything: "lifestolen.*"


# Item
# To see valid items, go to this website 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'

heart:
  itemName: "Heart" # Item name.
  itemLore: "This will give you one heart." # Item lore.
  isEnabled: true # Indicates if an item is enabled or disabled.
  disabledMessage: '&cThe heart item is disabled on this server.' # Message that appears if this item is disabled
  item: 'REDSTONE' # Item used for hearts
reviver:
  itemName: "Reviver" # Item name.
  itemLore: "This will revive someone." # Item lore.
  isEnabled: true # Indicates if an item is enabled or disabled.
  disabledMessage: '&cThe heart item is disabled on this server.' # Message that appears if this item is disabled
  item: 'BEACON' # Item used for hearts

# Banning

banTime: 86400 # Ban duration in seconds.
banReason: "&4You ran out of hearts." # The ban message.
kickMessage: "&4You ran out of hearts..." # Kick message for when you get banned.

# Crafting
# For reference. See this image to see each slots 'https://wiki.vg/images/7/7b/CraftingTable-slots.png' and this for material types 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'
# To make a blank spot, type 'AIR' in one of the slots
HeartRecipe:
  Slot1: "REDSTONE_BLOCK"
  Slot2: "REDSTONE_BLOCK"
  Slot3: "REDSTONE_BLOCK"
  Slot4: "REDSTONE_BLOCK"
  Slot5: "ENCHANTED_GOLDEN_APPLE"
  Slot6: "REDSTONE_BLOCK"
  Slot7: "AIR"
  Slot8: "REDSTONE_BLOCK"
  Slot9: "AIR"
ReviverRecipe:
  Slot1: "DIAMOND_BLOCK"
  Slot2: "DIAMOND_BLOCK"
  Slot3: "DIAMOND_BLOCK"
  Slot4: "EMERALD_BLOCK"
  Slot5: "NETHER_STAR"
  Slot6: "EMERALD_BLOCK"
  Slot7: "OBSIDIAN"
  Slot8: "OBSIDIAN"
  Slot9: "OBSIDIAN"