#  .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-. .-.-.  
#  '. L )'. i )'. f )'. e )'. S )'. t )'. o )'. l )'. e )'. n ) 
#    ).'   ).'   ).'   ).'   ).'   ).'   ).'   ).'   ).'   ).'
# Plugin by KadotCom
# Open-Source

# General
returnHP: 20 #  When a player is unbanned, their health will reset
MaxHP: 120 # HP that when reached, the player will not gain anymore health

# Permissions

permissions:
  # permission - The permission someone needs to run a permission based command.
  # permission-message - The message that appears when someone tries to run a command and doesn't have the correct permissions.
  # permissionToDoEverything - The permission someone needs to run all permission based commands.
  sethealth:
    permission: "lifestolen.sethealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  addhealth:
    permission: "lifestolen.sethealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  removehealth:
    permission: "lifestolen.removehealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  resethp:
    permission: "lifestolen.resethealth"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command."
  giveheart:
    permission: "lifestolen.giveheart"
    permission-message: "&f[&cLifeStolen&f] You don't have permission to use this command. You will have to craft a heart."
  permissionToDoEverything: "lifestolen.*"


# Item
# To see valid items, go to this website 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'

heartItem: 'REDSTONE' # Item used for hearts

# Banning

banTime: 86400 # Ban duration in seconds.
banReason: "&4You ran out of hearts." # The ban message.
kickMessage: "&4You ran out of hearts..." # Kick message for when you get banned.

# Crafting
# For reference. See this image to see each slots 'https://wiki.vg/images/7/7b/CraftingTable-slots.png' and this for material types 'https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html'
# To make a blank spot, type 'AIR' in one of the slots
HeartRecipe:
  Slot1: "REDSTONE_BLOCK"
  Slot2: "REDSTONE_BLOCK"
  Slot3: "REDSTONE_BLOCK"
  Slot4: "REDSTONE_BLOCK"
  Slot5: "ENCHANTED_GOLDEN_APPLE"
  Slot6: "REDSTONE_BLOCK"
  Slot7: "AIR"
  Slot8: "REDSTONE_BLOCK"
  Slot9: "AIR"
